### PR TITLE
Disable island fly on other worlds

### LINKED ISSUE #312: Island Flight works everywhere
**Describe the bug**
Players keep island fly in every world if they use /island fly.

**To Reproduce**
1. Use '/island fly' on island.
2. Use any teleportation command (/spawn, /warp, /tpa)
3. Boom, you have fly somewhere you shouldn't.

**Expected behavior**
Flight is toggled off with any teleportation command.

** Server Version and Plugin Version**
1.17.1, plugin 3.0.7

### PR DESCRIPTION
**Pull request by MertUnverdi**
fixes #312

### CODE REVIEW

**Comment by dlsf** [comment]
I think that the main issue is that flight is not disabled when switching worlds and that the timer continues to run out

**Comment by MertUnverdi** [comment]
> I think that the main issue is that flight is not disabled when switching worlds and that the timer continues to run out

may other users still on island also we can't stop timer :(

**Comment by dlsf** [comment]
But we can add condition to its logic

**Comment by dlsf** [comment]
I guess we could also just disable flight every time someone switches to a non IridiumSkyblock world + block /is fly in these

**Pull request closed without merging**
