### PR TITLE
Refactored Commands to make Ori Happy

### PR DESCRIPTION
**Pull request by PeachesMLG**
Thoughts?

### CODE REVIEW

**Comment by dlsf** [comment]
Use some empty lines between if statements, it looks pretty bad like this

**Comment by MertUnverdi** [comment]
I'm Confirm das' s comment ori is shit who matter him wants?

**Comment by dlsf** [comment]
Ori is good

**Comment by PeachesMLG** [comment]
:eyes: welp im too lazy to add the spaces, I just spent ages doing this and am too lazy to do that, so ima just merge and we can add spaces as we go, or you can do another pr or whatever if u want

**Pull request merged**
