### PR TITLE
Make rank names configurable

### PR DESCRIPTION
**Pull request by MertUnverdi**

### CODE REVIEW

**Comment by PeachesMLG** [comment]
I think there was a suggestion to make the items configurable, how about doing that instead?

**Comment by dlsf** [comment]
I agree, that'd probably be better

**Comment by MertUnverdi** [comment]
Ya its better, i'll do when at home thanks for reviews

**Comment by dlsf** [comment]
You should revert the changes from your previous attempt

**Comment by MertUnverdi** [comment]
Make new pr (i couldn't revert previous commits)

**Pull request closed without merging**
