### PR TITLE
Add Entity limits

### PR DESCRIPTION
**Pull request by MertUnverdi**
i think this is pretty unnecassary, but if you like merge it :p:

### CODE REVIEW

**Comment by dlsf** [comment]
This code looks like a bad idea... Adding all mobs from all worlds to a list, filtering it by checking the island and counting it - and all of that on every mob spawn - I don't think that'll work well.

**Comment by PeachesMLG** [comment]
What das said, if you doing this id use IslandManager#getEntities

**Comment by PeachesMLG** [comment]
Also add some sort of message about entity cap

**Comment by MertUnverdi** [comment]
@PeachesMLG IslandManager#getEntities works async? it seems worse but i u said i'll try :panda:

**Comment by MertUnverdi** [comment]
> Also add some sort of message about entity cap

sends to who one?

**Comment by Oribuin** [comment]
> sends to who one?

The person who made tried to place the block you 4head

**Comment by MertUnverdi** [comment]
> > sends to who one?
> 
> The person who made tried to place the block you 4head

stupid.

**Comment by MertUnverdi** [comment]
tf im not remember it lol

**Pull request closed without merging**
