### PR TITLE
Make default island colours based on Schematics

### PR DESCRIPTION
**Pull request by MertUnverdi**

### CODE REVIEW

**Comment by PeachesMLG** [comment]
I dont really see a need for this?

**Comment by dlsf** [comment]
Looks really unnecessary. We should add the schematic to the IslandCreateEvent though, if that's possible.

**Comment by MertUnverdi** [comment]
but, why not??? also this suggested on suggestions channel

**Comment by MertUnverdi** [comment]
it still a feature so can be added, if wont, close the pr i hate to wait "(

**Pull request closed without merging**
