### PR TITLE
Optimize SaveList

### PR DESCRIPTION
**Pull request by DoctaEnkoda**

### CODE REVIEW

**Comment by dlsf** [comment]
I don't really see how this optimizes anything? Streams are not as performant as normal loops, and it's not more readable either. 

As this is a performance-critical part of the code, I don't really like this change.

**Comment by DoctaEnkoda** [comment]
Old : 
```
[22:15:40 INFO]: [IridiumSkyblock] Disabling IridiumSkyblock v3.2.2
[22:15:40 INFO]: [IridiumSkyblock] Sauvegarde des Users
[22:15:40 INFO]: [IridiumSkyblock] Sauvegarde des Islands
[22:15:40 INFO]: [IridiumSkyblock] Sauvegarde des Invites
[22:15:40 INFO]: [IridiumSkyblock] Sauvegarde des Permissions
[22:15:40 INFO]: [IridiumSkyblock] Sauvegarde des Blocks
[22:16:10 INFO]: [IridiumSkyblock] Sauvegarde des Spawners
[22:16:12 INFO]: [IridiumSkyblock] Sauvegarde des Banks
[22:16:14 INFO]: [IridiumSkyblock] Sauvegarde des Missions
[22:16:15 INFO]: [IridiumSkyblock] Sauvegarde des Reward
[22:16:15 INFO]: [IridiumSkyblock] Sauvegarde des Upgrades
[22:16:20 INFO]: [IridiumSkyblock] Sauvegarde des Confiances
[22:16:20 INFO]: [IridiumSkyblock] Sauvegarde des Booster
[22:16:22 INFO]: [IridiumSkyblock] Sauvegarde des Warps
[22:16:22 INFO]: [IridiumSkyblock] Sauvegarde des Logs
container@pterodactyl~ Server marked as offline...
```
With this patch :
```
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Users
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/11207
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Islands
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/4927
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Invites
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/363
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Permissions
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/2763
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Spawners
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/4970
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Banks
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/11070
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Missions
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/3681
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Reward
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/171
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Upgrades
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/17933
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Confiances
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/180
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Booster
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/8637
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Warps
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/242
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Bans
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/92
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Blocks
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/298600
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Logs
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/330416
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Settings
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/29867
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde des Settings
[22:14:18 INFO]: [IridiumSkyblock] Sauvegarde faite : 0/29867
[22:14:18 INFO]: [IridiumSkyblock] Fin des sauvegardes
```

The performance gain is more than significant and does not break anything.
PS: for the first, pufferpanel kill the server because it no longer responds for several minutes.

**Comment by dlsf** [comment]
The time depends on the amount of data stored and the amount of changee data. I don't see how your code could cause such a giant speed increase - but maybe you have an answer to that question.

**Comment by DoctaEnkoda** [comment]
For loops are efficient when the data is small, conversely streams are more efficient when the data is very numerous.
After I agree on the readability level, the streams are less good but there we only ask for one condition.

**Comment by dlsf** [comment]
Streams being more efficient, even when looking at bigger amounts of data, would be news to me. Do you have a benchmark which confirms this claim?

**Comment by DoctaEnkoda** [comment]
With this code on my computer : 

```
public class Example {

    private static final List<PlayerClass> value = new ArrayList<>();

    public static void main(String []args) {
        for (int i = 0; i < 5000000; i++) {
            PlayerClass playerClass = new PlayerClass("name" + i, "username" + i, i);
            value.add(playerClass);
        }

        System.out.println("Loop when age < 500");
        long startLoop = System.currentTimeMillis();
        for (int i = 0; i < value.size(); i++) {
            PlayerClass player = value.get(i);
            if (player.years < 500) {}
        }
        long endLoop = System.currentTimeMillis();
        System.out.println("Stream when age < 500");
        long startStream = System.currentTimeMillis();
        value.stream().filter(playerClass -> playerClass.years < 500);
        long endStream = System.currentTimeMillis();

        System.out.println("Result\n" +
                "Loop: " + (endLoop - startLoop) + "ms\n" +
                "Stream: " + (endStream - startLoop) + "ms");
    }

    public static class PlayerClass {

        private final String name;
        private final String username;
        private final int years;

        public PlayerClass(String name1, String username1, int years1) {
            name = name1;
            username = username1;
            years = years1;
        }

        public String getName() {
            return name;
        }

        public String getUsername() {
            return username;
        }

        public int getYears() {
            return years;
        }
    }
}
```
> Task :Example.main()
Loop when age < 500
Stream when age < 500
Result
Loop: 53ms
Stream: 46ms

Corretto-16 16.0.2

**Comment by DoctaEnkoda** [comment]
```Java
package org.example;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Example {

    private static final List<PlayerClass> value = new ArrayList<>();

    public static void main(String []args) {
        for (int i = 0; i < 5000000; i++) {
            PlayerClass playerClass = new PlayerClass("name" + i, "username" + i, i);
            value.add(playerClass);
        }

        System.out.println("Loop when age < 500");
        long startLoop = System.currentTimeMillis();
        List<PlayerClass> test = new ArrayList<>();
        for (int i = 0; i < value.size(); i++) {
            PlayerClass player = value.get(i);
            if (player.years < 500) {
                test.add(player);
            }
        }
        long endLoop = System.currentTimeMillis();
        System.out.println("Stream when age < 500");
        long startStream = System.currentTimeMillis();
        List<PlayerClass> test2 = value.stream().filter(playerClass -> playerClass.years < 500).collect(Collectors.toList());
        long endStream = System.currentTimeMillis();

        System.out.println("Result\n" +
                "Loop: " + (endLoop - startLoop) + "ms\n" +
                "Stream: " + (endStream - startStream) + "ms");
    }

    public static class PlayerClass {

        private final String name;
        private final String username;
        private final int years;

        public PlayerClass(String name1, String username1, int years1) {
            name = name1;
            username = username1;
            years = years1;
        }

        public String getName() {
            return name;
        }

        public String getUsername() {
            return username;
        }

        public int getYears() {
            return years;
        }
    }
}
```
> Task :Example.main()
Loop when age < 500
Stream when age < 500
Result
Loop: 109ms
Stream: 76ms

I'm add a List for better check

**Comment by DoctaEnkoda** [comment]
```Java
package org.example;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Example {

    private static final List<PlayerClass> value = new ArrayList<>();

    public static void main(String []args) {
        for (int i = 0; i < 100; i++) {
            PlayerClass playerClass = new PlayerClass("name" + i, "username" + i, i);
            value.add(playerClass);
        }

        System.out.println("Loop when age < 5");
        long startLoop = System.currentTimeMillis();
        List<PlayerClass> test = new ArrayList<>();
        for (int i = 0; i < value.size(); i++) {
            PlayerClass player = value.get(i);
            if (player.years < 5) {
                test.add(player);
            }
        }
        long endLoop = System.currentTimeMillis();
        System.out.println("Stream when age < 5");
        long startStream = System.currentTimeMillis();
        List<PlayerClass> test2 = value.stream().filter(playerClass -> playerClass.years < 5).collect(Collectors.toList());
        long endStream = System.currentTimeMillis();

        System.out.println("Result\n" +
                "Loop: " + (endLoop - startLoop) + "ms\n" +
                "Stream: " + (endStream - startStream) + "ms");
    }

    public static class PlayerClass {

        private final String name;
        private final String username;
        private final int years;

        public PlayerClass(String name1, String username1, int years1) {
            name = name1;
            username = username1;
            years = years1;
        }

        public String getName() {
            return name;
        }

        public String getUsername() {
            return username;
        }

        public int getYears() {
            return years;
        }
    }
}

```
> Task :Example.main()
Loop when age < 5
Stream when age < 5
Result
Loop: 0ms
Stream: 5ms

**Review by PeachesMLG — APPROVED** [review]

**Pull request closed without merging**
