### PR TITLE
Added regenInventoryClear

### PR DESCRIPTION
**Pull request by sh0inx**
Added the config options clearInventoryOnRegen & clearEnderChestOnRegen to allow servers to clear player inventories when regenerating islands.

### CODE REVIEW

**Comment by CuBeR116** [comment]
Yes, the desired functionality. Players can endlessly recreate islands for themselves and transfer resources to their friends

**Comment by sh0inx** [comment]
yeah... that's why the PR was made...
do you have anything you'd like to contribute to the PR?

**Comment by CuBeR116** [comment]
Yes, it would also be forbidden to open a bank in other worlds of your choice.
If there are several worlds on the server, then players from different worlds can put crystals, money, experience in their bank.

Of course, if there is only SkyBlock on the server, then there will be no such problems.

**Comment by sh0inx** [comment]
actually it would be preferable for you to just join our discord server

**Pull request merged**
