### PR TITLE
Delete duplicates from Database

### PR DESCRIPTION
**Pull request by PeachesMLG**
Not sure if I like this or not since the code is 99% the same for each method, feels like I can do this with a loop or something but im too dum to figure it out

### CODE REVIEW

**Comment by dlsf** [comment]
There are also duplicate islands iirc

**Comment by PeachesMLG** [comment]
I havent seen duplicate islands before? and that wouldnt really matter too much anyways since the id is a primary key so you can have duplicate islands but the id's have to be different

**Review by dlsf — APPROVED** [review]
Looks better

**Comment by EvilInsid** [comment]
im testing iridium skyblock for my server, so far money randomly resets.... whats a good software to edit database files? and how often do you have to fix this?

**Pull request merged**
