### PR TITLE
Improve static factory methods of enums

### PR DESCRIPTION
**Pull request by dlsf**

### CODE REVIEW

**Comment by PeachesMLG** [comment]
Main issue is valueof throws an exception instead of returning null

**Comment by dlsf** [comment]
How do we handle null values at the moment? Wouldn't it be better to just return a fallback option?

**Comment by PeachesMLG** [comment]
no, if its null we just send the player a message like "Thats not a thing idot"

**Comment by dlsf** [comment]
I see, we would have to add a try-catch with this approach. What option do you prefer?

**Comment by PeachesMLG** [comment]
I feel like how we do it now is fine where we just return null

**Pull request closed without merging**
