### PR TITLE
Make portals are works when nether or end islands disabled

### PR DESCRIPTION
**Pull request by MertUnverdi**
Wont teleport if nether or end island is enabled but the portal is on a island world and island not present

### CODE REVIEW

**Comment by PeachesMLG** [comment]
Could u explain what this does? Im too dum to figure it out

**Comment by MertUnverdi** [comment]
> Could u explain what this does? Im too dum to figure it out

just merge it its fine 👍🏻

**Comment by MertUnverdi** [comment]
@dlsf could you explain it to 🍑  ?

**Comment by MertUnverdi** [comment]
Are u serious ????

**Pull request closed without merging**
