### PR TITLE
Add Island Regen and Delete Settings

### PR DESCRIPTION
**Pull request by MertUnverdi**

### CODE REVIEW

**Comment by PeachesMLG** [comment]
Has this been tested? Especially resetting boosters?

**Review by PeachesMLG — APPROVED** [review]

**Comment by PeachesMLG** [comment]
@dlsf could u review please <3

**Comment by dlsf** [comment]
I already did

**Comment by dlsf** [comment]
There are some nice options now but you can easily bypass them by just not being online... What's the point then

**Comment by PeachesMLG** [comment]
> There are some nice options now but you can easily bypass them by just not being online... What's the point then

:shrug: but ye it probabbly should clear all member's emderchets and inventories?
Also change
        public boolean clearInventories = true;
        public boolean clearEnderChests = true;
default to false please

**Review by PeachesMLG — CHANGES_REQUESTED** [review]
.

**Comment by MertUnverdi** [comment]
> > There are some nice options now but you can easily bypass them by just not being online... What's the point then
> 
> 🤷 but ye it probabbly should clear all member's emderchets and inventories?
> Also change
> public boolean clearInventories = true;
> public boolean clearEnderChests = true;
> default to false please

why i guess the default is should be true, but if you're sure i'll do :panda:

**Comment by MertUnverdi** [comment]
also the olds `clearInventoryOnRegen` and `clearEnderChestOnRegen` is be stay there, is there way to remove them from configs?

**Comment by MertUnverdi** [comment]
> Has this been tested? Especially resetting boosters?

i just slept when finished this didn't tested it yet sorry

**Comment by MertUnverdi** [comment]
ye i tested except island bans and invites, everything works :succes:

**Comment by PeachesMLG** [comment]
> also the olds `clearInventoryOnRegen` and `clearEnderChestOnRegen` is be stay there, i don't think but is there way to remove them from configs?

Just delete the variables from the Configuration.java class

**Comment by PeachesMLG** [comment]
> > > There are some nice options now but you can easily bypass them by just not being online... What's the point then
> > 
> > 
> > shrug but ye it probabbly should clear all member's emderchets and inventories?
> > Also change
> > public boolean clearInventories = true;
> > public boolean clearEnderChests = true;
> > default to false please
> 
> why i guess the default is should be true, but if you're sure i'll do :panda:

People are dum if we default to true people will complain about glitches that clear then inventory on regen

**Comment by MertUnverdi** [comment]
> > also the olds `clearInventoryOnRegen` and `clearEnderChestOnRegen` is be stay there, i don't think but is there way to remove them from configs?
> 
> Just delete the variables from the Configuration.java class

Peaches....
i already did that idiot, are u did check commits??
i mean removing from exitings configs

**Comment by MertUnverdi** [comment]
> > > > There are some nice options now but you can easily bypass them by just not being online... What's the point then
> > > 
> > > 
> > > shrug but ye it probabbly should clear all member's emderchets and inventories?
> > > Also change
> > > public boolean clearInventories = true;
> > > public boolean clearEnderChests = true;
> > > default to false please
> > 
> > 
> > why i guess the default is should be true, but if you're sure i'll do :panda:
> 
> People are dum if we default to true people will complain about glitches that clear then inventory on regen

Okay fine 👍🏻

**Review by PeachesMLG — CHANGES_REQUESTED** [review]
Still think clear inventories and clear enderchests should apply to all island members not just the person executing the command

**Comment by MertUnverdi** [comment]
> Still think clear inventories and clear enderchests should apply to all island members not just the person executing the command

is already???

**Comment by PeachesMLG** [comment]
my bad Ry is just dum

**Pull request merged**
