### PR TITLE
Fix warp messages & Fix ArrayIndexOutOfBoundsException

### LINKED ISSUE #178: When do /is deletewarp but i can't remake this error :/
https://pastebin.com/RrbX7EyZ

### PR DESCRIPTION
**Pull request by dlsf**
Fixes #178

### CODE REVIEW

**Comment by PeachesMLG** [comment]
Id rather keep the syntax /is warp <name> but we should probabbly add a prefix to the other ones

**Comment by dlsf** [comment]
I'm confused, what do you mean with that?

**Comment by dlsf** [comment]
We should distinguish between optional and required arguments. Looks pretty weird sometimes (for instance for /is bank) right now

**Comment by PeachesMLG** [comment]
> We should distinguish between optional and required arguments. Looks pretty weird sometimes (for instance for /is bank) right now

Ye i believe the convention is <> for required and () for optional ill add that tmr

**Pull request merged**
